server:
  port: 4444
eureka:
  instance:
    lease-renewal-interval-in-seconds: 20 #租期更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 60 #租期到期时间（默认90秒）
  client:
    healthcheck:
      enabled: true #开启健康检查（需要spring-boot-starter-actuator依赖）
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"