spring:
  application:
    name: organization-service
  profiles:
    active: ${env}

feign:
  hystrix:
    enabled: true

#admin client config
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"