server:
  port: 3333

eureka:
  client:
    serviceUrl:
      defaultZone: http://35.201.196.124:1111/eureka/
  instance:
    ip-address: 35.201.196.124 # 使用docker部署时 指定此实例的ip
    prefer-ip-address: true    # 注册时使用ip而不是主机名


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"